### ISSUE TITLE
What is it ?

### ISSUE THREAD

**Issue by RickZeeland** [JuergenGutsch/graphql-aspnetcore#1]
From the readme, it is not clear what **GraphQL** is or what it's use is, could you please enlighten us ?

**Comment by spicydonuts** [comment]
It's a syntax/language (usually on top of a REST endpoint) for decoupling the client/server relationship.  Clients can also statically validate whether all their requests will work against a given server and codegen type definitions for the client's language (TS, Flow, Swift, etc).  See [graphql.org](http://graphql.org)

**Comment by RickZeeland** [comment]
@spicydonuts Ah, much clearer now, maybe it can be useful for our API ...

**Comment by JuergenGutsch** [comment]
I'll add a short note about GraphQL to the readme, Thanks for that hint :)
