### ISSUE TITLE
GraphiQL not showing correctly

### ISSUE THREAD

**Issue by aalmada** [JuergenGutsch/graphql-aspnetcore#10]
When I execute the current solution in master and open the graphiql endpoint, it doesn't appear correctly as shown in this screenshot.

![2017-11-04 15_23_35-graphiql](https://user-images.githubusercontent.com/534533/32406660-426d3826-c174-11e7-8875-084210372779.png)

**Comment by JuergenGutsch** [comment]
Did you read the error message? Comment/Remove line 64 in the startup.cs.

**Comment by aalmada** [comment]
Sorry, I didn't notice the HTML was an error message. Thanks!
