### ISSUE TITLE
Request: Please provide Nuget packages.

### ISSUE THREAD

**Issue by amborle** [JuergenGutsch/graphql-aspnetcore#11]

**Comment by amborle** [comment]
For Graphiql

**Comment by JuergenGutsch** [comment]
Sure. As soon as I fixed the Build (#6)

**Comment by JohannesHoppe** [comment]
Until this is fixed - could you just upload the existing packages by hand, please? 👍

**Comment by JuergenGutsch** [comment]
@JohannesHoppe Do you really wanna use packages I built on my machine? ;-)
If the build is running on my machine, it'll run on AppVeyor anyway. Because of CAKE
Will do that later today :-)

**Comment by JohannesHoppe** [comment]
handcrafted nuget packages are the best ones! 😄 
... but I will try out the `development` branch now, too. 

I bet the build issue would go away if you configure it properly with an `appveyor.yml`. Just relying on conventions does not work with you folder structure.

**Comment by JohannesHoppe** [comment]
also, why cake?
I would expect:

```
dotnet build
dotnet test
dotnet publish
```

Full stop! ;-)

**Comment by JuergenGutsch** [comment]
"dotnet publish" just creates the packages and cake also has the "real" publishing features built in. And the other advantages of cake: I have the full control, I'm independent from the build server and I'm able to run the same build on my local machine.

Also, it's not allowed to push too often to NuGet, so I'm going to use MyGet instead for the "develop" builds und just push the builds from "master" to NuGet.

**Comment by JohannesHoppe** [comment]
>  I'm able to run the same build on my local machine.

I see. That's a good point. Circle, Travis, AppVeyor all are very proprietary and we have to test the builds online. 

If you change your mind, I like this example:
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/appveyor.yml#L29

**Comment by JuergenGutsch** [comment]
> ... all are very proprietary and we have to test the builds online.
Of course. Those round trips are always a time wasting pain. I do CI/CD since around 15 years using various kind of build servers and since a few years I really like way it works using CAKE or FAKE (or even using grunt, gulp or WebPack).

**Comment by JuergenGutsch** [comment]
The packages will be available later tomorrow. Need some more time to get it done the right way, but I'm almost done :-)

**Comment by JohannesHoppe** [comment]
👍

**Comment by JuergenGutsch** [comment]
[![Build status](https://ci.appveyor.com/api/projects/status/vxe22mwm1l2gw3b4?svg=true)](https://ci.appveyor.com/project/JuergenGutsch/graphql-aspnetcore)

The preview Packages are available on MyGet: https://www.myget.org/F/juergengutsch/api/v3/index.json

**Comment by JohannesHoppe** [comment]
Look nice. I might copy the conf for my Nuget package Mongo2Go. 😀
