### ISSUE TITLE
Query is too complex to execute.

### ISSUE THREAD

**Issue by JohannesHoppe** [JuergenGutsch/graphql-aspnetcore#12]
I just wanted to play around with the demo.
Steps to reproduce

1. Checkout  https://github.com/JuergenGutsch/graphql-aspnetcore/commit/11c7156799b2c9686b04c7994d35ed2387601249
2. Open .sln in VS2017, compile & debug `GraphQLDemo`
3. Open http://localhost:56416/graphiql
   Server sends immediately Exception:  `Internal Server Error`
```
An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (Query is too complex to execute. The field with the highest complexity is: FragmentSpread{name='FullType', directives=GraphQL.Language.AST.Directives})
GraphQl.AspNetCore.GraphQlMiddleware.CheckForErrors(ExecutionResult result) in GraphQlMiddleware.cs, line 85

Exception: Query is too complex to execute. The field with the highest complexity is: FragmentSpread{name='FullType', directives=GraphQL.Language.AST.Directives}
GraphQl.AspNetCore.GraphQlMiddleware.CheckForErrors(ExecutionResult result)
```
Thrown [here](https://github.com/JuergenGutsch/graphql-aspnetcore/blob/11c7156799b2c9686b04c7994d35ed2387601249/GraphQl.AspNetCore/GraphQlMiddleware.cs#L46). Because of the failed `IntrospectionQuery` GraphiQL gets into a bogus state, e.g auto-completion does not work any longer.

4. Now everything is screwed, e.g.
```
{
  books{
    isbn,
    name,
    author{
      id,
      name,
      birthdate
    }
  }
}
```
  (as shown here:  https://github.com/JuergenGutsch/graphql-aspnetcore/issues/3#issuecomment-314325842)

5. this works
```
{
  books{
    isbn,
    name
  }
}
```

Suggestion:
The demo should have a lower `ComplexityConfiguration`. It's pretty uncool that the demo starts with an exception. E.g:

```
options.ComplexityConfiguration = new ComplexityConfiguration { MaxDepth = 15 }; 
```

A small PR is following soon.

**Comment by JuergenGutsch** [comment]
Done in #13 @JohannesHoppe thanks for the fix
