### ISSUE TITLE
Demo incomplete - No QueryArgument for limit

### ISSUE THREAD

**Issue by JohannesHoppe** [JuergenGutsch/graphql-aspnetcore#14]
In your [blogpost](http://asp.net-hacker.rocks/2017/05/29/graphql-and-aspnetcore.html) you show the following example:

> The list is too large? Just limit the result, to get only 20 items:
```
{
  books(limit: 20) {
    isbn,
    name,
    author{
      id,
      name,
      birthdate
    }
  }
}
```

Problem:
This is not implemented in the demo, see [here](https://github.com/JuergenGutsch/graphql-aspnetcore/blob/97d5be0314b4c78b0b71400adbf04c58ba945dec/GraphQlDemo.Query/GraphQlTypes/BookQuery.cs) -- there is only a `QueryArgument` for `isbn`.

If I'm going to executing the query, the following error comes up:

```
An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (Unknown argument "limit" on field "books" of type "BooksQuery".)
GraphQl.AspNetCore.GraphQlMiddleware.CheckForErrors(ExecutionResult result) in GraphQlMiddleware.cs, line 85

Exception: Unknown argument "limit" on field "books" of type "BooksQuery".
GraphQl.AspNetCore.GraphQlMiddleware.CheckForErrors(ExecutionResult result)
```

**Comment by JuergenGutsch** [comment]
@JohannesHoppe yes, that's possible. In that blog post, I also added some examples about what is possible using GraphQL. Did you also check the develop branch? There are a lot of improvements, which are not yet merged to master.

**Comment by JohannesHoppe** [comment]
A lot of improvement in `developement` - for sure. Errors are much better readable.  Great. 😄 
But I was confused for a while, until I realized that the shown example was not implemented at all.

The new (readable error message): 
```
{
  "errors": [
    {
      "message": "Unknown argument \"limit\" on field \"books\" of type \"BooksQuery\".",
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ]
    }
  ]
}
```

;-)
