### ISSUE TITLE
options.RootGraphType must be a type

### ISSUE THREAD

**Issue by aminebizid** [JuergenGutsch/graphql-aspnetcore#17]
options.RootGraphType must be a type and not an instance in order to use DI.
In real world, bookrepo is a scoped service because it injects a DbContext.

```cs
options.RootGraphType = typeof(IBookRepository);
```

**Comment by JuergenGutsch** [comment]
Hi @aminebizid,
did you have a look into the develop branch? It already works as proposed in the develop branch :-)
