### ISSUE TITLE
Package GraphQl.AspNetCore 1.0.0-preview1 is not compatible with net461?

### ISSUE THREAD

**Issue by jiaxiangl** [JuergenGutsch/graphql-aspnetcore#2]
Can not install the nuget package to the api

![image](https://user-images.githubusercontent.com/22890806/27598022-d16e7a3c-5b29-11e7-8288-307327eac631.png)

**Comment by JuergenGutsch** [comment]
Do you use ASP.NET Core on .NET Framework or the classic ASP NET?
As I wrote, this is for ASP.NET Core. It uses features of ASP.NET Core and cannot be used in classic ASP.NET.

**Comment by jiaxiangl** [comment]
yeah, I am using asp.net core. but I am using VS2017 so it's no longer support project.json any more. Is this something that goes wrong here? 
Here's part of the csproj code that shows i am using asp.net core 
![image](https://user-images.githubusercontent.com/22890806/27601208-2133cb62-5b34-11e7-8deb-cbe40c04432f.png)

**Comment by JuergenGutsch** [comment]
ok, got it. Thanks for your feedback
This is an issue with the .NET Standard 1.6, which is not supported by .NET 4.6.1
(This will be a lot better if .NET Standard 2.0 is released)

I'm going to play around with a solution mentioned here: https://stackoverflow.com/a/43109941/94229

**Comment by JuergenGutsch** [comment]
Hi @jiaxiangl,
it would be a little more effort to support net461 and netstandard1.5 in one way. 
I would prefer to wait for netstandard2.0, which definitely will work with the .NET Framework. I played around with the preview the last weeks and it is really awesome. 

To get it running with net461 for the short term, I would propose to download the sources and build it on your machine for the .NET Framework. 

I'll leave this issue open until I get it running for both, netstandard and net.

**Comment by jiaxiangl** [comment]
Awesome, thanks for let me know!

**Comment by JuergenGutsch** [comment]
Since .NET Standard is available since a while and I actually provided the new packages on [MyGet](https://www.myget.org/F/juergengutsch/api/v3/index.json), I'm going to close this issue
