### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by dyesseyumba** [JuergenGutsch/graphql-aspnetcore#23]
Hi,
How to apply CORS policy for Graphql endpoint?

Best regards,
Dyesse.

**Comment by JuergenGutsch** [comment]
Hi @dyesseyumba,
I'll check it. Thanks for this issue.

**Comment by JuergenGutsch** [comment]
Hi @dyesseyumba 
Great. Many thanks for your investigation :-)
