### ISSUE TITLE
Multiple graphql endpoints

### ISSUE THREAD

**Issue by lszomoru** [JuergenGutsch/graphql-aspnetcore#24]
I am using "areas" in my ASP.NET Core application, and I am considering adding one graphql endpoint in each of the areas. Is it possible to use this middleware when adding multiple endpoints? Thanks!

**Comment by JuergenGutsch** [comment]
Hi @lszomoru,
It is possible to create multiple GraphQL endpoints. It should possible to add an endpoint per area then.
I never tried it unfortunately. Did you?
I'm pretty sure, we just need to ensure that there is no conflict between the GraphQL endpoint and the areas route. Because it the endpoint URIs are independent from the areas MVC routes.

**Comment by JuergenGutsch** [comment]
I think I got it :)
You are able to add multiple schema by adding multiple GraphQl configurations:

``` csharp
services.AddGraphQl(schema =>
                {
                    schema.Name = "Area1Schema"
                    schema.SetQueryType<Area1SchemaQuery>();
                });
services.AddGraphQl(schema =>
                {
                    schema.Name = "Area2Schema"
                    schema.SetQueryType<Area2SchemaQuery>();
                });
```

Than you should be able to add multiple middlewares like this:

``` csharp
app.UseGraphQl("/area1/graphql", options =>
                {
                    options.SchemaName = "Area1Schema";
                });
app.UseGraphQl("/area2/graphql", options =>
                {
                    options.SchemaName = "Area2Schema";
                });
```
Does it make sense to you?

**Comment by lszomoru** [comment]
Yep, that is why I was thinking of doing with the current implementation. The only wrinkle is that we are adding multiple instances of the same middleware to the ASP.NET core request pipeline. Ideally we would want to have only one instance of the middleware in the pipeline.

**Comment by lszomoru** [comment]
That makes sense. Please feel free to close out this issue.

**Comment by JuergenGutsch** [comment]
Yes, I think I'll close it.
Many thanks for this issue anyway :-)
