### ISSUE TITLE
FluentValidation integration

### ISSUE THREAD

**Issue by Rajivhost** [JuergenGutsch/graphql-aspnetcore#26]
Hi,
It would be great to have such support of FluentValidation on the pipe to easilly add validation for incoming mutations and queries like made [here](https://github.com/JeremySkinner/FluentValidation/wiki/i.-ASP.NET-Core-integration).

Best regards,
Rajiv.

**Comment by JuergenGutsch** [comment]
Hi @Rajivhost,
This is a really great proposal. I like it. Many thanks. 
I'm a huge fan of fluent APIs, so I definitely will have a look into it.
Cheers,
Juergen

**Comment by lextas** [comment]
I know this is an old issue but for those who are looking for an answer. I don't think FluentValidation should be added to the GraphQL pipeline but rather change the project structure to create a service layer. 

e.g:

```
// basic example

public class BookValidator : AbstractValidator<Book> 
{
	public BookValidator()
	{
		// add rules
	}
}

public class BookService : IBookService
{
	private readonly IBookRepository bookRepository;
	
	public BookService(IBookRepository bookRepository)
	{
		this.bookRepository = bookRepository;
	}
	
	public async Task<Book> CreateBookAsync(BookModel book)
	{
		var bookValidator = new BookValidator(();
		var validationResult = bookValidator.Validate(book);
		
		if(!validationResult.IsValid)
		{
			// do something with  validationResult.Errors
			// maybe throw an exception
		}
		
		var result = await this.bookRepository.Create(book);
		if(result == null)
		{
			// possibly throw exception (or let the repository throw an exception)
			// all depends on how you configure your exception handling
		}
		
		return result;
	}
}

public class BookRepository : IBookRepository
{
	public async Task<Book> Create(BookModel book)
	{
		// implement your logic here
	}
}
```
By using this approach you can reuse the service logic so you can support both _REST_ and _GraphQL_ with the same implementation and ables you to write _unit tests_ for it as well.

**Comment by JuergenGutsch** [comment]
Would you please create a PR? Would like to add this approach :-)
