### ISSUE TITLE
Unable to convert list of string from input

### ISSUE THREAD

**Issue by pouladpld** [JuergenGutsch/graphql-aspnetcore#27]
There is an issue with parsing input types of `ListGraphType<StringGraphType>`. Check last commit on this branch to reproduce the issue.

<https://github.com/pouladpld/graphql-aspnetcore/tree/string-list>

#### Request

`POST localhost:5000/graphql`
```json
{
    "query": "mutation FooMutation($foo: FooInput) { addFoo(foo: $foo) { bar, baz } }",
    "variables": {
        "foo": {
            "bar": "BAR",
            "baz": [ "BAZ", "baz" ]
        }
    }
}
```

#### Response
```json
{
    "errors": [
        {
            "message": "Cannot convert value to AST: BAZ"
        }
    ]
}
```

______________________

I'm still investigating it and will try to make a PR.
This seems to be the cause of problem in `GraphQL` package:

<https://github.com/graphql-dotnet/graphql-dotnet/issues/389>
<https://github.com/graphql-dotnet/graphql-dotnet/issues/394>

**Comment by JuergenGutsch** [comment]
Hi @pouladpld 

Thanks for this issue and your fix. I really appreciate that :)
