### ISSUE TITLE
Support to resolve instance of DocumentExecuter that were registered per scope

### ISSUE THREAD

**Issue by JuergenGutsch** [JuergenGutsch/graphql-aspnetcore#30]
Related to #29

This issue is also to decide whether we add the DocumentExecuter as singleton or as scoped instance to the IoC. It seems the IoC is not able to resolve the DocumentExecuter from scope, even if the MiddleWare is running in the default ASP.NET Core pipeline.
(We should also do some investigation on why it is not working)

**Comment by pouladpld** [comment]
Looking at `GraphQL-DotNet` example and `DocumentExecuter` class, I believe registering it with IoC container as singleton is fine.

<https://github.com/graphql-dotnet/graphql-dotnet/blob/43a0160fa86110ca884fe86885a764e1daa40bd0/src/GraphQL.GraphiQLCore/Startup.cs#L17>

<https://github.com/graphql-dotnet/graphql-dotnet/blob/43a0160fa86110ca884fe86885a764e1daa40bd0/src/GraphQL/Execution/DocumentExecuter.cs#L20-L34>

**Comment by pouladpld** [comment]
Also, the problem in _failure in resolving from root scope_ is that there is no scope created [at this point](https://github.com/JuergenGutsch/graphql-aspnetcore/blob/94953f7db48398c0bd73d3970a6a5d0bcaca59d4/GraphQlDemo/Startup.cs#L74).

If we need to resolve that for each HTTP request's scope, we should resolve it from `HttpContext` servcies inside `MyMiddleware.Invoke()` method.

**Comment by JuergenGutsch** [comment]
yes, you are right. Thanks :)
