### ISSUE TITLE
Mistake in the README.md?

### ISSUE THREAD

**Issue by peterbucher** [JuergenGutsch/graphql-aspnetcore#32]
I think there is a mistake in the README.md file: https://github.com/JuergenGutsch/graphql-aspnetcore/blob/develop/README.md

On the paragraph:

`Changes on the master branch ("current version" branch) will be pushed as preview releases to NuGet. To see whether this branch is stable, follow the builds on AppVeyor: Build status`

Does't it mean "will be pushed as releases to NuGet" instead of "preview releases"?

**Comment by JuergenGutsch** [comment]
Thanks @peterbucher,
I just fixed it :)
