### ISSUE TITLE
Scope Issue

### ISSUE THREAD

**Issue by Rajivhost** [JuergenGutsch/graphql-aspnetcore#34]
Hi @JuergenGutsch,
Can you please publish a new beta release to have the latest changes regarding Scope fixes.

Best regards,
Rajiv.

**Comment by JuergenGutsch** [comment]
Hi @Rajivhost 
actually there is a new beta release on MyGet:
https://www.myget.org/F/juergengutsch/api/v3/index.json
This gets automatically be done, every time there is a change on the develop branch.

Best,
Juergen
