### ISSUE TITLE
Allow for tab indentation

### ISSUE THREAD

**Issue by waterfoul** [JuergenGutsch/graphql-aspnetcore#35]
The settings view only allows for space based indentation. All of our other languages are setup for tab indents. Please provide this option

**Comment by waterfoul** [comment]
![image](https://user-images.githubusercontent.com/2756150/40067331-91e4cbc8-582b-11e8-8d7c-7a559bd54f01.png)

**Comment by JuergenGutsch** [comment]
Got it. Thanks for clarification :-)

Personally I prefer spaces over tabs, to not have two different kind of white-space characters used in the code files. **This is IMHO the default setting in Visual Studio and I'd like to keep that.**

To ensure to use the spaces in my repos, I should add a editor.config to enforce all the editors to use it. Thanks for the hint :-)

**Comment by waterfoul** [comment]
Sure and having a spaces option as default makes sense. I would just like the option for using tabs

**Comment by JuergenGutsch** [comment]
An interesting option. Do you have an idea about how to enable tabs and spaces at the same time? At least the tabs need to be converted to spaces on commit.

**Comment by waterfoul** [comment]
*Sigh* I just realized I posted this in the wrong repo. I apologize and will reopen in the correct place
