### ISSUE TITLE
Consider implementing Caching

### ISSUE THREAD

**Issue by vertonghenb** [JuergenGutsch/graphql-aspnetcore#36]
By definition GraphQL can't use caching of routes, since it's always the same route. The following is just an idea to implement a Cache in the middleware component.

If we intercept every query coming to the server, create a hash and store it in a lookup table. the next time the request comes in(in x amount of seconds), simply return the cached item instead of resolving the entire query.

**Comment by JuergenGutsch** [comment]
Hey @vertonghenb 
After thinking about this for a while, I think this is not in the scope of the middleware itself. I wouldn't do that in the middleware. Caching may be done in the repositories or services which feed schema. 

If I would do that, I also need to think about and cache dependencies, which means It is not only about the request that comes in, but also about the data that may change during the lifetime of the cache.

Feel free to implement caching by yourself on the service level.
