### ISSUE TITLE
publish 1.1.4 to nuget

### ISSUE THREAD

**Issue by stylefish** [JuergenGutsch/graphql-aspnetcore#53]
hi, 
i'm using you library in one of my projects but i have to use the 1.1.4 version because i'm overriding the DocumentBuilder to return a custom document :).
would it be possible to publish that version to nuget? because every time i use the project i have to get the package from myget... 
if not, do you have an idea on when a new release (even if its prerelease) gets published to the official nuget feed? 
thanks in advance and keep up the great work! :)
greetings

**Comment by JuergenGutsch** [comment]
Hi @stylefish 
Glad you like the library :-)
Since this is just a personal side project, it is kinda hard to plan.
But I think 1.1.4 is stable and can be released on NuGet. I'll do within the next days. I'll definitely find some time the next days.
Thanks

**Comment by JuergenGutsch** [comment]
I just released 1.1.4 on Nuget. 
1.1.5 is now the version I work on.
